### ISSUE TITLE
NextJS tutorial: Add mergify and validation steps to the new nextjs tutorial repo, protect main branch, etc.

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-tutorial#11061]
```[tasklist]
### Tasks
- [x] Update settings to match carbon-tutorial
- [x] add mergify.yml
- [ ] add reviewers automatically
- [x] compare PR checks with https://github.com/carbon-design-system/carbon-tutorial/pull/11073
- [x] add circleci config file https://github.com/carbon-design-system/carbon-tutorial-nextjs/pull/10
- [x] add licence file
- [x] add contents for .github folder
```
